/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Phonic from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Updated appointment details",
 *         prompt: "Updated extraction instructions. Dates should be in `9 Apr 2025` format.",
 *         fields: [{
 *                 name: "Date",
 *                 type: "string",
 *                 description: "The date of the appointment"
 *             }, {
 *                 name: "Time",
 *                 type: "string",
 *                 description: "The time of the appointment"
 *             }]
 *     }
 */
export interface UpdateExtractionSchemaRequest {
    /** The name of the project containing the extraction schema. Only used when `nameOrId` is a name. */
    project?: string;
    /** A name for the extraction schema. */
    name?: string;
    /** Instructions for how to extract data from conversations. */
    prompt?: string;
    /** Array of field definitions. */
    fields?: Phonic.ExtractionField[];
}
