// This file was auto-generated by Fern from our API Definition.

import type * as Phonic from "../../../../index.js";

/**
 * @example
 *     {
 *         project: "main",
 *         description: "Updated description for booking appointments with enhanced features",
 *         endpoint_headers: {
 *             "Authorization": "Bearer updated_token456"
 *         },
 *         endpoint_timeout_ms: 7000
 *     }
 */
export interface UpdateToolRequest {
    /** The name of the project containing the tool. Only used when `nameOrId` is a name. */
    project?: string;
    /** The name of the tool. Must be snake_case and unique within the organization. */
    name?: string;
    /** A description of what the tool does. */
    description?: string;
    /** Mode of operation. */
    execution_mode?: UpdateToolRequest.ExecutionMode;
    /** The static context returned to the agent. Only applicable to custom_context tools. */
    context?: string;
    /**
     * The tool's parameters, either as a flat array of parameter definitions or as a raw JSON Schema object (use the object form for nested parameters). Replaces the tool's existing parameters, including the form they are stored in.
     * For `custom_webhook` tools: when sending an array, `location` is required for POST and defaults to `"query_string"` for GET, and `parameter_locations` must not be sent; when sending a JSON Schema object, placement is supplied in `parameter_locations`.
     * For `custom_websocket`, `built_in_transfer_to_phone_number`, and `built_in_transfer_to_agent` tools: `location` must not be specified.
     */
    parameters?: UpdateToolRequest.Parameters;
    /**
     * Where each top-level parameter is sent in the webhook request, as a map from parameter name to location. Only for `custom_webhook` tools whose `parameters` are a raw JSON Schema object.
     * Can be sent on its own to move existing parameters without resending `parameters`; entries are merged over the tool's current placement, so parameters left out keep where they were.
     * Every key must name a top-level parameter. For POST webhooks, every parameter needs a placement. For GET webhooks, unplaced parameters default to `"query_string"` and `"request_body"` is not allowed.
     */
    parameter_locations?: Record<string, UpdateToolRequest.ParameterLocations.Value>;
    /** HTTP method for webhook tools. When switching from POST to GET, a tool with request body parameters must also send new `parameters` (or `parameter_locations`) placing them in the query string. */
    endpoint_method?: UpdateToolRequest.EndpointMethod;
    /** URL for webhook tools. Must be a publicly routable HTTPS URL without embedded credentials. */
    endpoint_url?: string;
    /** Headers for webhook tools. Set to null to clear existing headers. */
    endpoint_headers?: Record<string, string | null> | null;
    endpoint_timeout_ms?: number;
    tool_call_output_timeout_ms?: number;
    /** The E.164 formatted phone number to transfer calls to. Set to null if the agent should determine the phone number. */
    phone_number?: string | null;
    /** DTMF digits to send after the transfer connects (e.g., "1234"). Can be set to null to remove DTMF. Ignored when dynamic_dtmf is true. */
    dtmf?: string | null;
    /** Fixed line the agent speaks into the bridged call once the transfer connects. Can be set to null to remove the announcement. Must be null when the resulting keep_listening is false. Only applicable to built_in_transfer_to_phone_number tools. */
    post_transfer_message?: string | null;
    /** When true, the agent determines the DTMF digits at call time (and may choose to send none); the static dtmf is ignored. Only sent when use_agent_phone_number is true (not on a SIP REFER transfer). */
    dynamic_dtmf?: boolean;
    /** When true, Phonic will transfer the call using the agent's phone number. When false, Phonic will transfer the call using the phone number of the party to whom the agent is connected. This is only available for built_in_transfer_to_phone_number tools. */
    use_agent_phone_number?: boolean;
    /** When true, Phonic will listen in and tell the user if the transfer hits voicemail. This is only available for built_in_transfer_to_phone_number tools when use_agent_phone_number is true. */
    detect_voicemail?: boolean;
    /** When true, Phonic bridges the transfer and stays on the call. When false, the call is handed off with a SIP REFER and Phonic drops out, which requires the resulting use_agent_phone_number and detect_voicemail to be false, dtmf and post_transfer_message to be null and dynamic_dtmf to be false. Only applicable to built_in_transfer_to_phone_number tools. */
    keep_listening?: boolean;
    /** Array of agent names that the LLM can choose from when transferring. All agents must exist in the same project as the tool. */
    agents_to_transfer_to?: string[];
    /** When true, forces the agent to speak before executing the tool. */
    require_speech_before_tool_call?: boolean;
    /** For built_in_natural_conversation_ending and built_in_keypad_input tools. Whether the agent must speak before calling the tool ("required"), the model decides ("optional"), or the agent must stay silent ("suppressed"). Not used by other tool types. */
    speech_before_tool_call?: UpdateToolRequest.SpeechBeforeToolCall;
    /** For built_in_choose_not_to_respond tools. Number of seconds to wait after the tool fires before the agent speaks a follow-up if the user stays silent. When null, the agent stays silent (default). Not used by other tool types. */
    respond_after_sec?: number | null;
    /** If true, the agent will wait to finish speaking before executing the tool. This is only available for custom_webhook and custom_websocket tools. */
    wait_for_speech_before_tool_call?: boolean;
    /** When true, forbids the agent from speaking after executing the tool. Available for custom_context, custom_webhook and custom_websocket tools. */
    forbid_speech_after_tool_call?: boolean;
    /** When true, forbids the agent from calling the tool right after it has spoken. Available for custom_webhook and custom_websocket tools. */
    forbid_tool_call_after_speech?: boolean;
    /** When true, allows the agent to chain and execute other tools after executing the tool. Available for custom_context, custom_webhook and custom_websocket tools. */
    allow_tool_chaining?: boolean;
    /** The agent doesn't typically wait for the response of async tools. When true, makes the agent wait for a response, not call other tools and inform the user of the result. Only available for async custom_webhook and custom_websocket tools, and cannot be combined with allow_tool_chaining set to true. */
    wait_for_response?: boolean;
}

export namespace UpdateToolRequest {
    /** Mode of operation. */
    export const ExecutionMode = {
        Sync: "sync",
        Async: "async",
    } as const;
    export type ExecutionMode = (typeof ExecutionMode)[keyof typeof ExecutionMode];
    /**
     * The tool's parameters, either as a flat array of parameter definitions or as a raw JSON Schema object (use the object form for nested parameters). Replaces the tool's existing parameters, including the form they are stored in.
     * For `custom_webhook` tools: when sending an array, `location` is required for POST and defaults to `"query_string"` for GET, and `parameter_locations` must not be sent; when sending a JSON Schema object, placement is supplied in `parameter_locations`.
     * For `custom_websocket`, `built_in_transfer_to_phone_number`, and `built_in_transfer_to_agent` tools: `location` must not be specified.
     */
    export type Parameters = Phonic.ToolParameter[] | Phonic.ToolParametersJsonSchema;

    export namespace ParameterLocations {
        export const Value = {
            RequestBody: "request_body",
            QueryString: "query_string",
        } as const;
        export type Value = (typeof Value)[keyof typeof Value];
    }

    /** HTTP method for webhook tools. When switching from POST to GET, a tool with request body parameters must also send new `parameters` (or `parameter_locations`) placing them in the query string. */
    export const EndpointMethod = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type EndpointMethod = (typeof EndpointMethod)[keyof typeof EndpointMethod];
    /** For built_in_natural_conversation_ending and built_in_keypad_input tools. Whether the agent must speak before calling the tool ("required"), the model decides ("optional"), or the agent must stay silent ("suppressed"). Not used by other tool types. */
    export const SpeechBeforeToolCall = {
        Required: "required",
        Optional: "optional",
        Suppressed: "suppressed",
    } as const;
    export type SpeechBeforeToolCall = (typeof SpeechBeforeToolCall)[keyof typeof SpeechBeforeToolCall];
}
