/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ConversationsExtractDataResponse {
    /** The extracted data according to the schema. */
    result: Record<string, unknown>;
}
