/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ConversationsSipOutboundCallResponse {
    /** The ID of the created conversation. */
    conversation_id: string;
    /** The Twilio Call SID. */
    twilio_call_sid: string;
}
