/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface AgentsGetRequest {
    /**
     * The name of the project containing the agent. Only used when `nameOrId` is a name.
     */
    project?: string;
}
