/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Phonic from "../../../../index.js";

/**
 * @example
 *     {
 *         project: "main",
 *         name: "support-agent",
 *         phone_number: "assign-automatically",
 *         timezone: "America/Los_Angeles",
 *         voice_id: "grant",
 *         audio_speed: 1,
 *         background_noise_level: 0,
 *         welcome_message: "Hi {{customer_name}}. How can I help you today?",
 *         system_prompt: "You are an expert in {{subject}}. Be friendly, helpful and concise.",
 *         template_variables: {
 *             "customer_name": {},
 *             "subject": {
 *                 default_value: "Chess"
 *             }
 *         },
 *         tools: ["keypad_input"],
 *         no_input_poke_sec: 30,
 *         no_input_poke_text: "Are you still there?",
 *         recognized_languages: ["en", "es"],
 *         boosted_keywords: ["Load ID", "dispatch"],
 *         configuration_endpoint: {
 *             url: "https://api.example.com/config",
 *             headers: {
 *                 "Authorization": "Bearer token123"
 *             },
 *             timeout_ms: 7000
 *         }
 *     }
 */
export interface UpsertAgentRequest extends Phonic.CreateAgentRequest {
    /** The name of the project containing the agent. */
    project?: string;
}
