// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         text: "x"
 *     }
 */
export interface StreamTtsRequest {
    /** The text to convert to speech. */
    text: string;
    /** The TTS model to use. */
    model?: "merritt";
    /** The speech speed. */
    speed?: number;
    /** The voice ID to use. */
    voice_id?: string;
    /** The audio format to stream. */
    output_format?: StreamTtsRequest.OutputFormat;
}

export namespace StreamTtsRequest {
    /** The audio format to stream. */
    export const OutputFormat = {
        Pcm44100: "pcm_44100",
        Pcm16000: "pcm_16000",
        Pcm8000: "pcm_8000",
        Mulaw8000: "mulaw_8000",
    } as const;
    export type OutputFormat = (typeof OutputFormat)[keyof typeof OutputFormat];
}
