// This file was auto-generated by Fern from our API Definition.

import type * as Phonic from "../index.js";

/**
 * A built-in tool with an explicit configuration, as an alternative to referencing it by bare name (which uses the tool's default configuration). Only `keypad_input` and `natural_conversation_ending` accept configuration this way.
 */
export interface BuiltInToolDefinition {
    type: "built_in";
    /** The name of the built-in tool. */
    name: BuiltInToolDefinition.Name;
    tool_config: Phonic.BuiltInToolConfig;
}

export namespace BuiltInToolDefinition {
    /** The name of the built-in tool. */
    export const Name = {
        KeypadInput: "keypad_input",
        NaturalConversationEnding: "natural_conversation_ending",
    } as const;
    export type Name = (typeof Name)[keyof typeof Name];
}
