// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration fields for the initial `config` message.
 */
export interface ConfigOptions {
    /** Agent name to use for conversation */
    agent?: string | undefined;
    /** Project name */
    project?: string | undefined;
    /** STS model to use */
    model?: "merritt" | undefined;
    /** System prompt for AI assistant */
    system_prompt?: string | undefined;
    /** Audio playback speed */
    audio_speed?: number | undefined;
    /** Background noise level for the conversation */
    background_noise_level?: number | undefined;
    /** Background noise type for the conversation */
    background_noise?: (ConfigOptions.BackgroundNoise | null) | undefined;
    /** When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored. */
    generate_welcome_message?: boolean | undefined;
    /** Message to play when conversation starts. Ignored when `generate_welcome_message` is `true`. */
    welcome_message?: (string | null) | undefined;
    /** Voice ID to use for speech synthesis */
    voice_id?: string | undefined;
    /** Audio input format */
    input_format?: ConfigOptions.InputFormat | undefined;
    /** Audio output format */
    output_format?: ConfigOptions.OutputFormat | undefined;
    /** Voice activity detection prebuffer duration */
    vad_prebuffer_duration_ms?: number | undefined;
    /** Minimum speech duration for VAD */
    vad_min_speech_duration_ms?: number | undefined;
    /** Minimum silence duration for VAD */
    vad_min_silence_duration_ms?: number | undefined;
    /** Voice activity detection threshold */
    vad_threshold?: number | undefined;
    /** Minimum number of words required to interrupt the assistant. */
    min_words_to_interrupt?: number | undefined;
    /** Whether to have the no-input poke text be generated by AI */
    generate_no_input_poke_text?: boolean | undefined;
    /** Seconds of silence before poke message */
    no_input_poke_sec?: (number | null) | undefined;
    /** Poke message text. Ignored when generate_no_input_poke_text is true. */
    no_input_poke_text?: string | undefined;
    /** Seconds of silence before ending conversation */
    no_input_end_conversation_sec?: number | undefined;
    /** ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language. */
    default_language?: string | undefined;
    /** Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`. */
    additional_languages?: string[] | undefined;
    /** If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended). */
    multilingual_mode?: ConfigOptions.MultilingualMode | undefined;
    /** Keywords to boost in speech recognition */
    boosted_keywords?: string[] | undefined;
    /** Names of tools available to the assistant. */
    tools?: ConfigOptions.Tools.Item[] | undefined;
    /** Template variables for system prompt and welcome message */
    template_variables?: Record<string, string> | undefined;
}

export namespace ConfigOptions {
    /** Background noise type for the conversation */
    export const BackgroundNoise = {
        Office: "office",
        CallCenter: "call-center",
        CoffeeShop: "coffee-shop",
    } as const;
    export type BackgroundNoise = (typeof BackgroundNoise)[keyof typeof BackgroundNoise];
    /** Audio input format */
    export const InputFormat = {
        Pcm44100: "pcm_44100",
        Pcm16000: "pcm_16000",
        Pcm8000: "pcm_8000",
        Mulaw8000: "mulaw_8000",
    } as const;
    export type InputFormat = (typeof InputFormat)[keyof typeof InputFormat];
    /** Audio output format */
    export const OutputFormat = {
        Pcm44100: "pcm_44100",
        Pcm16000: "pcm_16000",
        Pcm8000: "pcm_8000",
        Mulaw8000: "mulaw_8000",
    } as const;
    export type OutputFormat = (typeof OutputFormat)[keyof typeof OutputFormat];
    /** If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended). */
    export const MultilingualMode = {
        Auto: "auto",
        Request: "request",
    } as const;
    export type MultilingualMode = (typeof MultilingualMode)[keyof typeof MultilingualMode];
    export type Tools = Tools.Item[];

    export namespace Tools {
        export type Item = string | Record<string, unknown>;
    }
}
