// This file was auto-generated by Fern from our API Definition.

export interface ConversationEvaluationResult {
    /** The evaluation ID. */
    id: string;
    /** The evaluation result. */
    result: ConversationEvaluationResult.Result;
    /** The evaluation prompt information. */
    prompt: ConversationEvaluationResult.Prompt;
    /** When the evaluation was created. */
    created_at: string;
}

export namespace ConversationEvaluationResult {
    /** The evaluation result. */
    export const Result = {
        Successful: "successful",
        Unsuccessful: "unsuccessful",
        Undecided: "undecided",
        Error: "error",
    } as const;
    export type Result = (typeof Result)[keyof typeof Result];

    /**
     * The evaluation prompt information.
     */
    export interface Prompt {
        id: string;
        name: string;
    }
}
