/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ConversationEval {
    /** The evaluation result. */
    result: ConversationEval.Result;
    /** The evaluation prompt used. */
    prompt: string;
}

export namespace ConversationEval {
    /**
     * The evaluation result.
     */
    export type Result = "successful" | "unsuccessful" | "undecided";
    export const Result = {
        Successful: "successful",
        Unsuccessful: "unsuccessful",
        Undecided: "undecided",
    } as const;
}
