/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ConversationEvalPrompt {
    /** The evaluation prompt ID. */
    id: string;
    /** The evaluation prompt name. */
    name: string;
    /** The evaluation prompt text. */
    prompt: string;
}
