// This file was auto-generated by Fern from our API Definition.

export interface ConversationsListResponseConversationsPagination {
    /** Cursor to fetch the previous page of conversations (newer). Use this value in the `before` query parameter. `null` if there is no previous page. */
    prev_cursor: string | null;
    /** Cursor to fetch the next page of conversations (older). Use this value in the `after` query parameter. `null` if there is no next page. */
    next_cursor: string | null;
}
