// This file was auto-generated by Fern from our API Definition.

export interface ConversationItem {
    /** Index of the item in the conversation. */
    item_idx: number;
    /** Who spoke in this turn. */
    role: ConversationItem.Role;
    /** Live transcript of this turn. */
    live_transcript: string;
    /** Post-call processed transcript. */
    post_call_transcript: string | null;
    /** Duration of this turn in milliseconds. */
    duration_ms: number;
    /** When this turn started. */
    started_at: string;
    /** Voice ID used (assistant only). */
    voice_id?: string | undefined;
    /** Audio speed used (assistant only). */
    audio_speed?: number | undefined;
    /** System prompt used for this assistant turn. */
    system_prompt?: string | undefined;
    /** Tool calls made by the assistant. */
    tool_calls?: ConversationItem.ToolCalls.Item[] | undefined;
}

export namespace ConversationItem {
    /** Who spoke in this turn. */
    export const Role = {
        User: "user",
        Assistant: "assistant",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
    export type ToolCalls = ToolCalls.Item[];

    export namespace ToolCalls {
        export interface Item {
            /** The tool call ID. */
            id: string;
            tool: Item.Tool;
            /** HTTP method for webhook tool calls. */
            endpoint_method?: (string | null) | undefined;
            /** URL for webhook tool calls. */
            endpoint_url?: (string | null) | undefined;
            /** Headers for webhook tool calls. */
            endpoint_headers?: (Record<string, string | null> | null) | undefined;
            /** Timeout in milliseconds for webhook tool calls. */
            endpoint_timeout_ms?: (number | null) | undefined;
            /** When the webhook endpoint was called (null on error). */
            endpoint_called_at?: (string | null) | undefined;
            /** Query parameters for webhook tool calls (null on error or when no params). */
            query_params?: (Record<string, unknown> | null) | undefined;
            /** HTTP response status code for webhook tool calls (null on error). */
            response_status_code?: (number | null) | undefined;
            /** Timeout in milliseconds for websocket tool calls. */
            tool_call_output_timeout_ms?: (number | null) | undefined;
            /** The request body sent to the tool. Can be any JSON-serializable value. */
            request_body: Item.RequestBody | null;
            /** The response body received from the tool. */
            response_body: Record<string, unknown> | null;
            /** Whether the tool call timed out. */
            timed_out: boolean | null;
            /** Error message if the tool call failed. */
            error_message: string | null;
        }

        export namespace Item {
            export interface Tool {
                /** The tool ID. */
                id: string;
                /** The tool name. */
                name: string;
            }

            /**
             * The request body sent to the tool. Can be any JSON-serializable value.
             */
            export type RequestBody = Record<string, unknown> | unknown[] | string | number | boolean;
        }
    }
}
