/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Phonic from "../index.js";

export interface Conversation {
    /** The conversation ID. */
    id: string;
    /** The agent associated with the conversation. */
    agent?: Conversation.Agent;
    /** The organization/workspace name. */
    workspace: string;
    /** External ID for conversation tracking. */
    external_id?: string;
    /** The STS model used. */
    model: string;
    /** Welcome message played at start. */
    welcome_message?: string;
    /** Audio input format. */
    input_format: string;
    /** Audio output format. */
    output_format: string;
    /** Live transcript of the conversation. */
    live_transcript: string;
    /** Post-call processed transcript. */
    post_call_transcript?: string;
    /** Duration of the conversation in milliseconds. */
    duration_ms: number;
    /** Presigned URL to the conversation audio file. */
    audio_url?: string;
    /** When the conversation started. */
    started_at: string;
    /** When the conversation ended. */
    ended_at?: string;
    /** System prompt used for the conversation. */
    system_prompt: string;
    /** Array of conversation items (turns). */
    items: Phonic.ConversationItem[];
    /** Results from conversation evaluations and extractions. */
    task_results: Record<string, unknown>;
}

export namespace Conversation {
    /**
     * The agent associated with the conversation.
     */
    export interface Agent {
        /** The ID of the agent. */
        id: string;
        /** The name of the agent. */
        name: string;
    }
}
