/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateLatentRequest {
    /** The voice ID. */
    voice_id: string;
    /** The codec name. */
    codec_name: string;
}
