// This file was auto-generated by Fern from our API Definition.

export interface DtmfPayload {
    type: "dtmf";
    /** DTMF digits to play */
    digits: string;
    /** Optional latency-breakdown metrics for the message, expressed as named millisecond durations. */
    timings?: Record<string, number> | undefined;
}
