// This file was auto-generated by Fern from our API Definition.

export interface GenerateReplyPayload {
    type: "generate_reply";
    /** Optional system message to guide the assistant's reply */
    system_message?: (string | null) | undefined;
}
