// This file was auto-generated by Fern from our API Definition.

export interface GeneratedToolCall {
    /** Identifier for this tool call. Send it back as the `tool_call_id` of the matching `tool_call_output` input item. */
    tool_call_id: string;
    /** Name of the tool to call. Always one of the `tool_definitions` from the request. */
    tool_name: string;
    /** Arguments the assistant produced for the request body. */
    request_body?: Record<string, unknown> | undefined;
    /** Arguments the assistant produced as query parameters. */
    query_params?: Record<string, string> | undefined;
}
