/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InterruptedResponsePayload {
    type: "interrupted_response";
    /** Truncated AI response text at interruption point */
    text: string;
}
