/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IsUserSpeakingPayload {
    type: "is_user_speaking";
    /** Whether user is currently speaking */
    is_user_speaking: boolean;
}
