/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ISO 639-1 language codes supported by the agent
 */
export type LanguageCode =
    | "ar"
    | "zh"
    | "cs"
    | "da"
    | "nl"
    | "en"
    | "fr"
    | "de"
    | "id"
    | "it"
    | "ja"
    | "ko"
    | "pl"
    | "pt"
    | "ru"
    | "es"
    | "sv"
    | "tr"
    | "vi";
export const LanguageCode = {
    Ar: "ar",
    Zh: "zh",
    Cs: "cs",
    Da: "da",
    Nl: "nl",
    En: "en",
    Fr: "fr",
    De: "de",
    Id: "id",
    It: "it",
    Ja: "ja",
    Ko: "ko",
    Pl: "pl",
    Pt: "pt",
    Ru: "ru",
    Es: "es",
    Sv: "sv",
    Tr: "tr",
    Vi: "vi",
} as const;
