// This file was auto-generated by Fern from our API Definition.

import type * as Phonic from "../index.js";

/**
 * When an `agent` is provided, these `config` options override the agent settings.
 */
export interface OutboundCallConfig {
    /** The name of the agent to use for the call. */
    agent?: string | undefined;
    /** The name of the project to use for the call. */
    project?: string | undefined;
    /** Message to play when the conversation starts. Can contain template variables like `{{customer_name}}`. */
    welcome_message?: (string | null) | undefined;
    /** Instructions for the conversation. Can contain template variables like `{{subject}}`. */
    system_prompt?: string | undefined;
    /** Variables that can be used in the welcome message and the system prompt. */
    template_variables?: Record<string, string> | undefined;
    /** The voice ID to use for the agent. */
    voice_id?: string | undefined;
    /** Whether to have the no-input poke text be generated by AI. */
    generate_no_input_poke_text?: boolean | undefined;
    /** Number of seconds of silence before sending a poke message. `null` disables the poke message. */
    no_input_poke_sec?: (number | null) | undefined;
    /** The message to send after the specified silence. Ignored when generate_no_input_poke_text is true. */
    no_input_poke_text?: string | undefined;
    /** Seconds of silence before ending the conversation. */
    no_input_end_conversation_sec?: number | undefined;
    /** Array of ISO 639-1 language codes that the agent should be able to recognize */
    languages?: Phonic.LanguageCode[] | undefined;
    /** These words, or short phrases, will be more accurately recognized by the agent. */
    boosted_keywords?: string[] | undefined;
    /** Array of built-in or custom tool names to use. */
    tools?: OutboundCallConfig.Tools.Item[] | undefined;
}

export namespace OutboundCallConfig {
    export type Tools = Tools.Item[];

    export namespace Tools {
        export type Item =
            | "keypad_input"
            | "natural_conversation_ending"
            /**
             * Custom tool */
            | string;
    }
}
