// This file was auto-generated by Fern from our API Definition.

/**
 * The assistant stayed silent instead of responding (the `choose_not_to_respond` built-in tool).
 */
export interface ResponsesChoseNotToRespondAction {
    /** Number of seconds the assistant would wait before speaking a follow-up if the user stays silent, echoed from the tool's configuration. When null, the assistant stays silent. */
    respond_after_sec?: (number | null) | undefined;
}
