// This file was auto-generated by Fern from our API Definition.

export interface SipOutboundCallInitiatedResponse {
    /** The ID of the created conversation. */
    conversation_id: string;
    /** The Twilio Call SID. */
    twilio_call_sid: string;
    /** Always false when a call was placed. */
    dry_run: false;
}
