// This file was auto-generated by Fern from our API Definition.

export interface ToolCallOutputProcessedPayload {
    type: "tool_call_output_processed";
    /** ID of the completed tool call */
    tool_call_id: string;
    tool: ToolCallOutputProcessedPayload.Tool;
    /** Configuration of the tool that was called */
    tool_config?: (Record<string, unknown> | null) | undefined;
    /** HTTP method used for webhook endpoint (null for WebSocket tools) */
    endpoint_method?: (string | null) | undefined;
    /** Webhook endpoint URL (null for WebSocket tools) */
    endpoint_url?: (string | null) | undefined;
    /** Webhook timeout in milliseconds (null for WebSocket tools) */
    endpoint_timeout_ms?: (number | null) | undefined;
    /** When webhook was called (null for WebSocket tools) */
    endpoint_called_at?: (string | null) | undefined;
    /** Query string parameters sent to webhook endpoint (null for WebSocket tools) */
    query_params?: (Record<string, string | null> | null) | undefined;
    /** Webhook request body (null for WebSocket tools) */
    request_body?: (Record<string, unknown> | null) | undefined;
    /** Webhook response body (null for WebSocket tools) */
    response_body?: (unknown | null) | undefined;
    /** WebSocket tool parameters (null for webhook tools) */
    parameters?: (Record<string, unknown> | null) | undefined;
    /** WebSocket tool output (null for webhook tools) */
    output?: (unknown | null) | undefined;
    /** Webhook HTTP status code (null for WebSocket tools) */
    response_status_code?: (number | null) | undefined;
    /** Duration of the tool call in milliseconds */
    duration_ms?: (number | null) | undefined;
    /** Whether the tool call timed out */
    timed_out?: (boolean | null) | undefined;
    /** Error message if tool call failed */
    error_message?: (string | null) | undefined;
}

export namespace ToolCallOutputProcessedPayload {
    export interface Tool {
        /** Tool ID */
        id: string;
        /** Human-readable tool name */
        name: string;
    }
}
