/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToolCallOutputPayload {
    type: "tool_call_output";
    /** ID of the tool call being responded to */
    tool_call_id: string;
    output?: unknown;
}
