/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthCreateSessionTokenResponse {
    /** The session token to use for authentication. */
    session_token: string;
    /** When the session token expires. */
    expires_at: string;
}
