/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExtractionSchemasDeleteResponse {
    /** Whether the extraction schema was deleted successfully. */
    success: boolean;
}
