/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExtractionSchemasUpdateResponse {
    /** Whether the extraction schema was updated successfully. */
    success: boolean;
}
