/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         schema_id: "conv_extract_schema_6458e4ac-533c-4bdf-8e6d-c2f06f87fd5c"
 *     }
 */
export interface ExtractDataRequest {
    /** ID of the extraction schema to use. */
    schema_id: string;
}
