// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         project: "main"
 *     }
 */
export interface ExternalStoragePoliciesListRequest {
    /** The name of the project to list external storage policies for. */
    project?: string;
}
