// This file was auto-generated by Fern from our API Definition.

import * as Phonic from "../../src/api/index";
import { PhonicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ApiKeysClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "production-key" };
        const rawResponseBody = {
            id: "api_key_12cf6e88-c254-4d3e-a149-a7f1bdd22783",
            name: "production-key",
            api_key: "phk_abc123def456...",
        };

        server
            .mockEndpoint()
            .post("/api_keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.create({
            name: "production-key",
        });
        expect(response).toEqual({
            id: "api_key_12cf6e88-c254-4d3e-a149-a7f1bdd22783",
            name: "production-key",
            api_key: "phk_abc123def456...",
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api_keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.create({
                name: "name",
            });
        }).rejects.toThrow(Phonic.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api_keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.create({
                name: "name",
            });
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api_keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.create({
                name: "name",
            });
        }).rejects.toThrow(Phonic.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { success: true };

        server.mockEndpoint().delete("/api_keys/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKeys.delete("id");
        expect(response).toEqual({
            success: true,
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server.mockEndpoint().delete("/api_keys/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.delete("id");
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/api_keys/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.delete("id");
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server.mockEndpoint().delete("/api_keys/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.delete("id");
        }).rejects.toThrow(Phonic.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "renamed-key" };
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .patch("/api_keys/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.update("id", {
            name: "renamed-key",
        });
        expect(response).toEqual({
            success: true,
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api_keys/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Phonic.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api_keys/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api_keys/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/api_keys/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.update("id", {
                name: "name",
            });
        }).rejects.toThrow(Phonic.InternalServerError);
    });

    test("rotate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            id: "api_key_12cf6e88-c254-4d3e-a149-a7f1bdd22783",
            name: "production-key",
            api_key: "phk_new789xyz...",
        };

        server
            .mockEndpoint()
            .post("/api_keys/id/rotate")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.rotate("id");
        expect(response).toEqual({
            id: "api_key_12cf6e88-c254-4d3e-a149-a7f1bdd22783",
            name: "production-key",
            api_key: "phk_new789xyz...",
        });
    });

    test("rotate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api_keys/id/rotate")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.rotate("id");
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("rotate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api_keys/id/rotate")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.rotate("id");
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("rotate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api_keys/id/rotate")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.rotate("id");
        }).rejects.toThrow(Phonic.InternalServerError);
    });
});
