// This file was auto-generated by Fern from our API Definition.

import * as Phonic from "../../src/api/index";
import { PhonicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ConversationItemsClient", () => {
    test("replay (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { system_prompt: "system_prompt" };
        const rawResponseBody = {
            responses: [
                {
                    text: "Sure — I can help with that. What time works best?",
                    tool_calls: [{ tool: { id: "id", name: "name" }, request_body: null }],
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/conversation_items/id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.conversationItems.replay("id", {
            system_prompt: "system_prompt",
        });
        expect(response).toEqual({
            responses: [
                {
                    text: "Sure \u2014 I can help with that. What time works best?",
                    tool_calls: [
                        {
                            tool: {
                                id: "id",
                                name: "name",
                            },
                            request_body: null,
                        },
                    ],
                },
            ],
        });
    });

    test("replay (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { system_prompt: "system_prompt" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversation_items/id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversationItems.replay("id", {
                system_prompt: "system_prompt",
            });
        }).rejects.toThrow(Phonic.BadRequestError);
    });

    test("replay (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { system_prompt: "system_prompt" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/conversation_items/id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversationItems.replay("id", {
                system_prompt: "system_prompt",
            });
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("replay (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { system_prompt: "system_prompt" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversation_items/id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversationItems.replay("id", {
                system_prompt: "system_prompt",
            });
        }).rejects.toThrow(Phonic.ForbiddenError);
    });

    test("replay (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { system_prompt: "system_prompt" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversation_items/id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversationItems.replay("id", {
                system_prompt: "system_prompt",
            });
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("replay (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { system_prompt: "system_prompt" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/conversation_items/id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversationItems.replay("id", {
                system_prompt: "system_prompt",
            });
        }).rejects.toThrow(Phonic.ConflictError);
    });

    test("replay (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { system_prompt: "system_prompt" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/conversation_items/id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversationItems.replay("id", {
                system_prompt: "system_prompt",
            });
        }).rejects.toThrow(Phonic.UnprocessableEntityError);
    });

    test("replay (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { system_prompt: "system_prompt" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/conversation_items/id/replay")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.conversationItems.replay("id", {
                system_prompt: "system_prompt",
            });
        }).rejects.toThrow(Phonic.InternalServerError);
    });
});
