// This file was auto-generated by Fern from our API Definition.

import * as Phonic from "../../src/api/index";
import { PhonicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ExternalStoragePoliciesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            external_storage_policies: [
                {
                    id: "external_storage_policy_9c5f7d2a-4b18-4d0e-8a2e-7a2f1c6d3b90",
                    name: "conversation_archive",
                    endpoint_url: "https://storage.example.com",
                    bucket: "conversation-audio",
                    region: "us-east-1",
                    key_prefix: "phonic/conversations",
                    addressing_style: "auto",
                    agent_count: 2,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/external_storage_policies")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.externalStoragePolicies.list({
            project: "main",
        });
        expect(response).toEqual({
            external_storage_policies: [
                {
                    id: "external_storage_policy_9c5f7d2a-4b18-4d0e-8a2e-7a2f1c6d3b90",
                    name: "conversation_archive",
                    endpoint_url: "https://storage.example.com",
                    bucket: "conversation-audio",
                    region: "us-east-1",
                    key_prefix: "phonic/conversations",
                    addressing_style: "auto",
                    agent_count: 2,
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/external_storage_policies")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.list();
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/external_storage_policies")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.list();
        }).rejects.toThrow(Phonic.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {
            name: "conversation_archive",
            endpoint_url: "https://storage.example.com",
            bucket: "conversation-audio",
            region: "us-east-1",
            key_prefix: "phonic/conversations",
            addressing_style: "auto",
            access_key_id: "AKIAIOSFODNN7EXAMPLE",
            secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
        };
        const rawResponseBody = {
            id: "external_storage_policy_9c5f7d2a-4b18-4d0e-8a2e-7a2f1c6d3b90",
            name: "conversation_archive",
        };

        server
            .mockEndpoint()
            .post("/external_storage_policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.externalStoragePolicies.create({
            project: "main",
            name: "conversation_archive",
            endpoint_url: "https://storage.example.com",
            bucket: "conversation-audio",
            region: "us-east-1",
            key_prefix: "phonic/conversations",
            addressing_style: "auto",
            access_key_id: "AKIAIOSFODNN7EXAMPLE",
            secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
        });
        expect(response).toEqual({
            id: "external_storage_policy_9c5f7d2a-4b18-4d0e-8a2e-7a2f1c6d3b90",
            name: "conversation_archive",
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {
            name: "name",
            endpoint_url: "endpoint_url",
            bucket: "bucket",
            access_key_id: "access_key_id",
            secret_access_key: "secret_access_key",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/external_storage_policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.create({
                name: "name",
                endpoint_url: "endpoint_url",
                bucket: "bucket",
                access_key_id: "access_key_id",
                secret_access_key: "secret_access_key",
            });
        }).rejects.toThrow(Phonic.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {
            name: "name",
            endpoint_url: "endpoint_url",
            bucket: "bucket",
            access_key_id: "access_key_id",
            secret_access_key: "secret_access_key",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/external_storage_policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.create({
                name: "name",
                endpoint_url: "endpoint_url",
                bucket: "bucket",
                access_key_id: "access_key_id",
                secret_access_key: "secret_access_key",
            });
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {
            name: "name",
            endpoint_url: "endpoint_url",
            bucket: "bucket",
            access_key_id: "access_key_id",
            secret_access_key: "secret_access_key",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/external_storage_policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.create({
                name: "name",
                endpoint_url: "endpoint_url",
                bucket: "bucket",
                access_key_id: "access_key_id",
                secret_access_key: "secret_access_key",
            });
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {
            name: "name",
            endpoint_url: "endpoint_url",
            bucket: "bucket",
            access_key_id: "access_key_id",
            secret_access_key: "secret_access_key",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/external_storage_policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.create({
                name: "name",
                endpoint_url: "endpoint_url",
                bucket: "bucket",
                access_key_id: "access_key_id",
                secret_access_key: "secret_access_key",
            });
        }).rejects.toThrow(Phonic.ConflictError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {
            name: "name",
            endpoint_url: "endpoint_url",
            bucket: "bucket",
            access_key_id: "access_key_id",
            secret_access_key: "secret_access_key",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/external_storage_policies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.create({
                name: "name",
                endpoint_url: "endpoint_url",
                bucket: "bucket",
                access_key_id: "access_key_id",
                secret_access_key: "secret_access_key",
            });
        }).rejects.toThrow(Phonic.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            external_storage_policy: {
                id: "external_storage_policy_9c5f7d2a-4b18-4d0e-8a2e-7a2f1c6d3b90",
                name: "conversation_archive",
                endpoint_url: "https://storage.example.com",
                bucket: "conversation-audio",
                region: "us-east-1",
                key_prefix: "phonic/conversations",
                addressing_style: "auto",
                agent_count: 2,
            },
        };

        server
            .mockEndpoint()
            .get("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.externalStoragePolicies.get("nameOrId", {
            project: "main",
        });
        expect(response).toEqual({
            external_storage_policy: {
                id: "external_storage_policy_9c5f7d2a-4b18-4d0e-8a2e-7a2f1c6d3b90",
                name: "conversation_archive",
                endpoint_url: "https://storage.example.com",
                bucket: "conversation-audio",
                region: "us-east-1",
                key_prefix: "phonic/conversations",
                addressing_style: "auto",
                agent_count: 2,
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.get("nameOrId");
        }).rejects.toThrow(Phonic.ForbiddenError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.get("nameOrId");
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.get("nameOrId");
        }).rejects.toThrow(Phonic.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .delete("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.externalStoragePolicies.delete("nameOrId", {
            project: "main",
        });
        expect(response).toEqual({
            success: true,
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.delete("nameOrId");
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.delete("nameOrId");
        }).rejects.toThrow(Phonic.ForbiddenError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.delete("nameOrId");
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.delete("nameOrId");
        }).rejects.toThrow(Phonic.ConflictError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/external_storage_policies/nameOrId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.delete("nameOrId");
        }).rejects.toThrow(Phonic.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { bucket: "conversation-audio-archive", key_prefix: "phonic/archive" };
        const rawResponseBody = { success: true };

        server
            .mockEndpoint()
            .patch("/external_storage_policies/nameOrId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.externalStoragePolicies.update("nameOrId", {
            project: "main",
            bucket: "conversation-audio-archive",
            key_prefix: "phonic/archive",
        });
        expect(response).toEqual({
            success: true,
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/external_storage_policies/nameOrId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.update("nameOrId");
        }).rejects.toThrow(Phonic.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/external_storage_policies/nameOrId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.update("nameOrId");
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/external_storage_policies/nameOrId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.update("nameOrId");
        }).rejects.toThrow(Phonic.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/external_storage_policies/nameOrId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.update("nameOrId");
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/external_storage_policies/nameOrId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.update("nameOrId");
        }).rejects.toThrow(Phonic.ConflictError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/external_storage_policies/nameOrId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.externalStoragePolicies.update("nameOrId");
        }).rejects.toThrow(Phonic.InternalServerError);
    });
});
