// This file was auto-generated by Fern from our API Definition.

import * as Phonic from "../../src/api/index";
import { PhonicClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("VoicesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            voices: [
                {
                    id: "sabrina",
                    name: "Sabrina",
                    description: null,
                    audio_url: "https://example.com/audio/sabrina.wav",
                },
            ],
        };

        server.mockEndpoint().get("/voices").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.voices.list({
            model: "merritt",
        });
        expect(response).toEqual({
            voices: [
                {
                    id: "sabrina",
                    name: "Sabrina",
                    description: null,
                    audio_url: "https://example.com/audio/sabrina.wav",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/voices").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.voices.list({
                model: "merritt",
            });
        }).rejects.toThrow(Phonic.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/voices").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.voices.list({
                model: "merritt",
            });
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/voices").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.voices.list({
                model: "merritt",
            });
        }).rejects.toThrow(Phonic.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {
            voice: {
                id: "sabrina",
                name: "Sabrina",
                description: null,
                audio_url: "https://example.com/audio/sabrina.wav",
            },
        };

        server.mockEndpoint().get("/voices/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.voices.get("id");
        expect(response).toEqual({
            voice: {
                id: "sabrina",
                name: "Sabrina",
                description: null,
                audio_url: "https://example.com/audio/sabrina.wav",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/voices/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.voices.get("id");
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/voices/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.voices.get("id");
        }).rejects.toThrow(Phonic.NotFoundError);
    });

    test("preview (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {
            text: "Thanks for calling Phonic. How can I help?",
            voice_id: "grant",
            output_format: "pcm_16000",
        };
        const rawResponseBody = { audio: "audio" };

        server
            .mockEndpoint()
            .post("/tts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.voices.preview({
            text: "Thanks for calling Phonic. How can I help?",
            voice_id: "grant",
            output_format: "pcm_16000",
        });
        expect(response).toEqual({
            audio: "audio",
        });
    });

    test("preview (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/tts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.preview({
                text: "x",
            });
        }).rejects.toThrow(Phonic.BadRequestError);
    });

    test("preview (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/tts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.preview({
                text: "x",
            });
        }).rejects.toThrow(Phonic.UnauthorizedError);
    });

    test("preview (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/tts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.preview({
                text: "x",
            });
        }).rejects.toThrow(Phonic.ForbiddenError);
    });

    test("preview (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PhonicClient({
            maxRetries: 0,
            apiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/tts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.voices.preview({
                text: "x",
            });
        }).rejects.toThrow(Phonic.InternalServerError);
    });
});
